apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orange-project
  namespace:  argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: orange
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: fruits/orange
    repoURL: https://github.com/kunal2791/cldcvr.git
    targetRevision: main