apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "canary-preview.kunal.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: canary-demo
            port:
              number: 80