apiVersion: v1
kind: Service
metadata:
  name: mango-project
spec:
  type: ClusterIP
  ports:
  - name: "bind-frontend"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: mango-project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mango-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mango-project
  template:
    metadata:
      labels:
        app: mango-project
    spec:
      containers:
        - name: nginx
          image: kunal2791/mango:v3
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mango-project
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: a2a0f84efe0a24d3e8e6d90a5ef8aed7-79232029.eu-central-1.elb.amazonaws.com
      http:
        paths:
          - path: /mango
            pathType: Prefix
            backend:
              service:
                name: mango-project
                port:
                  number: 80