---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-server
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-autoscaler/
    repoURL: https://github.com/kjha27/cldcvr.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true