apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./ingress-nginx/charts/ingress-nginx/
    repoURL: https://github.com/kjha27/cldcvr.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true