---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    path: observablity/Grafana/loki-stack/
    repoURL: https://github.com/kjha27/cldcvr.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true