---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace:  argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace:  argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: helm-charts/charts/loki-stack/
    repoURL: https://github.com/kunal2791/cldcvr.git
    targetRevision: main
