apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampleapp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: sampleapp/helm
    repoURL: https://github.com/kunal2791/cldcvr.git
    targetRevision: main
#updated image tag with 10
#updated image tag with 11
#updated image tag with 12
#updated image tag with 13
#updated image tag with 14
