apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampleapp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: sampleapp/helm
    repoURL: https://github.com/kunal2791/cldcvr.git
    targetRevision: main

#updated image tag with 17
#updated image tag with 18
#updated image tag with 19
#updated image tag with 20
#updated image tag with 21
