apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name }}-fe
  namespace: {{.Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{.Values.name }}-fe
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.name }}-fe
    spec:
      containers:
      - name: {{.Values.name }}-fe
        image: {{.Values.fe.image }}:{{.Values.fe.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{.Values.fe.port }}
         