apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.name }}-fe
  namespace: {{.Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx-internal
spec:
  rules:
  - host: a3c2cfeea30754925bdbc08fdc1d41dd-8c2fbc507df78602.elb.eu-central-1.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.name }}-fe
            port:
              name: bind-frontend