apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name }}-fe
  namespace: {{.Values.namespace }}
  labels:
    service: {{.Values.name }}-fe
spec:
  type: ClusterIP
  selector:
    app: {{.Values.name }}-fe
  ports:
  - name: "bind-frontend"
    protocol: "TCP"
    port: {{.Values.fe.port }}
    targetPort: {{.Values.fe.port }}
  