apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{.Values.name }}-fe
spec:
  replicas: {{.Values.replica }}
  template:
    metadata:
      labels:
        app: {{.Values.name }}-fe
    spec:
      containers:
      - name: {{.Values.name }}-fe
        image: {{.Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{.Values.name.fe.containerPort }}
