name: Deploy Fruits to EKS

on:
  workflow_dispatch:
    inputs:
      fruits:
        type: choice
        description: 'Select fruits to deploy'
        options:
        - apple
        - orange
        - banana
        - mango
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EKS
      run: |
        echo "Selected fruit: ${{ github.event.inputs.fruits }}"
        # Use kubectl or eksctl to deploy the selected fruit to EKS
        #kubectl apply -f aps/${{ github.event.inputs.fruits }}.yaml
