name: Deploy to ECR
on:
  push:
    branches: [ main ]
    paths:
      - 'sampleapp/frontend/Dockerfile' 
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: sampleapp
        IMAGE_TAG: ${{ github.run_number }}
        IMAGE_TAG2: ${{github.sha}}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f sampleapp/frontend/Dockerfile .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG2 -f sampleapp/frontend/Dockerfile .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:frontend -f sampleapp/frontend/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
    - name: Create local changes
      run: |
        sed -e 's/tag: .*$/tag: ${{ github.run_number }}/g' ./sampleapp/helm/values.yaml
        git add ./sampleapp/helm/values.yaml
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
